### ISSUE TITLE
Contribution to JATS-Con 2015

### ISSUE THREAD

**Issue by Daniel-Mietchen** [data-citation-working-group/data-citation-workshop-2014#9]
"
your paper "Adapting JATS for data citation" has been accepted for JATS-Con. You are scheduled to present on Wednesday, April 22 at 9:00 am.

Please check your abstract http://jats.nlm.nih.gov/jats-con/2015/schedule2015a.html and the biographies linked from this page. I'll be happy to make any corrections you have.

Full papers in XML are due by March 13, 2015. The submission guidelines are here: http://jats.nlm.nih.gov/jats-con/submission-guidelines.html. Please let me know if you have any questions or problems along the way. I've pasted in feedback from the reviewers that may be helpful as you put together the full paper and your presentation.

If you have not yet registered for the conference, you can do so here at any time: http://jats.nlm.nih.gov/jats-con/forms/JATSregistration.html 
"

Reviews:
"
# Reviewer 1:

Issues related to data citation are important in general - and I can only believe that the JATS Con audience must find these issues to be particularly important. Hearing that FORCE11 is more directly engaging with the issue (beyond the Joint Declaration of Data Citation Principles) is great and I'm looking forward to seeing this talk.
# Reviewer 2:

I assume you already intend to do so, but please be sure to delve into the use cases behind these specific elements when explaining the decision criteria behind the elements proposed for inclusion in d2.
"

**Comment by Klortho** [comment]
Paper being drafted here: https://docs.google.com/document/d/1YJZrGtupPd-OqWiEjPsvi56h72xMC3p5jDc_kceoMk8/edit#

**Comment by Klortho** [comment]
Preliminary paper is now live, at [http://www.ncbi.nlm.nih.gov/books/NBK280240/](http://www.ncbi.nlm.nih.gov/books/NBK280240/).

**Comment by Klortho** [comment]
If someone could make me a collaborator on this repo, or, better yet, a member of this organization, I could close this issue.
